config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

	devise_scope :user do
	  authenticated :user do
	    root 'home#index', as: :authenticated_root
	  end

	  unauthenticated do
	    root 'devise/sessions#new', as: :unauthenticated_root
	  end
	end

  scope '/admin' do
    # Home Controller Starts
    get '/home/index', to: 'home#index'
    # Home Controller Ends

    # Users Controller Starts
    get '/employees', to: 'users#index'
    post '/employees', to: 'users#create'
    get '/employees/new', to: 'users#new', as: 'new_employee'
    get '/employees/:id/edit', to: 'users#edit', as: 'edit_employee'
    get '/employees/:id', to: 'users#show', as: 'employee'
    patch '/employees/:id', to: 'users#update'
    put 'employees/:id', to: 'users#update'
    delete 'employees/:id', to: 'users#destroy'

    get '/fetch_roles', to: 'roles#fetch_roles'
    # Users Controller Ends

    resources :roles, except: [:show]
    resources :categories, except: [:show]
    resources :products, except: [:show]
  end
  
  get '*page', :to => 'errors#not_found', as: :not_found
  get '*page', :to => 'errors#unacceptable', as: :unacceptable
  get '*page', :to => 'errors#internal_error', as: :internal_error
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  has_and_belongs_to_many :permissions, :join_table => :users_permissions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :assign_default_role

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

	validates_presence_of :name, :email

  accepts_nested_attributes_for :roles

  accepts_nested_attributes_for :permissions
  
  def assign_default_role
  	users = User.all
  	if users.count == 1
  		add_role(:super_admin) if self.roles.blank?
  	# else
  	# 	add_role(:normal) if self.roles.blank?
  	end
  end

  def self.from_omniauth(auth)
    # data = access_token.info
    # user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    # unless user
    #     user = User.create(name: data['name'],
    #        email: data['email'],
    #        password: Devise.friendly_token[0,20]
    #     )
    # end
    # user
    debugger
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  # def self.find_or_create_from_auth_hash(auth)
  #   where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
  #     user.provider = auth.provider
  #     user.uid = auth.uid
  #     user.first_name = auth.info.first_name
  #     user.last_name = auth.info.last_name
  #     user.email = auth.info.email
  #     user.picture = auth.info.image
  #     user.save!
  #   end
  # end

  # def self.from_omniauth(auth)
  #   # Either create a User record or update it based on the provider (Google) and the UID   
  #   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  #     user.token = auth.credentials.token
  #     user.expires = auth.credentials.expires
  #     user.expires_at = auth.credentials.expires_at
  #     user.refresh_token = auth.credentials.refresh_token
  #   end
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    debugger
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      debugger
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      debugger
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :set_params, only: [:create]
	before_action :set_user, only: [:show, :edit, :update, :destroy]
	before_action :get_controllers, only: [:new, :edit]

	def index
		@users = User.includes(:roles)
	end

	def show
	end

	def new
		@user = User.new
		@user.roles.build
		@user.permissions.build
	end

	def create
		generated_password = @passwrd
		roles = []
		roles = params[:user][:roles].compact
		roles = roles.reject { |e| e.to_s.empty? }
		user = User.new(user_params)
		if user.save
			# Save user credentials to file Starts (Only for testing purpose)
			save_user_cred(generated_password)
			# Save user credentials to file End
			add_user_roles(user, roles)

			redirect_to employees_path, notice: 'User is successfully created.'
		else
			render 'new'
		end
	end

	def edit
		begin
			if !@user.roles.present?
				@user.roles.build
			end
		rescue Exception => e
		end
	end

	def update
		roles = []
		roles = params[:user][:roles].compact
		roles = roles.reject { |e| e.to_s.empty? }
		if @user.update_attributes(user_update_params)
			@user.roles.each do |role|
	      @user.remove_role(role.name.to_sym)
	    end
	    add_user_roles(@user, roles)
	    redirect_to employees_path, notice: 'User is successfully updated.'
		else
			render 'edit'
		end
	end

	def destroy
		@user.destroy
		redirect_to employees_path, notice: 'User is successfully d: []estroyed.'
	end

	private

		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation, permission_ids: [])
		end

		def user_update_params
			params.require(:user).permit(:name, :email, permission_ids: [])
		end

		def set_params
			@passwrd = Devise.friendly_token.first(8)
			params[:user][:password] = @passwrd
			params[:user][:password_confirmation] = @passwrd
		end

		def set_user
			@user = User.find_by(id: params[:id])
		end

		def add_user_roles(user, roles)
			roles.each do |role|
				user.add_role(role.to_sym)
			end
		end

		def save_user_cred(pass)
			user_cred = {}
			user_cred[:email]=params[:user][:email]
			user_cred[:password]=pass
			file = File.open(Rails.public_path.join('user_cred.txt'), "a")
			file.puts user_cred.to_s
			file.close
		end

		def get_controllers
			@controller_types = Permission.all.map(&:controller_type).uniq
		end
end

app/helpers/users_helper.rb
module UsersHelper
	def get_roles(user)
		roles = ""
		if user.roles.present?
			user.roles.each do |role|
				roles += role.name + ", "
			end
			return roles
		end
	end
end

app/views/users/_form.html.erb
<%= form_for @user, as: :user, url: path, :html => {:class => "user_form"} do |f| %>
	<div class="form-group">
		<%= f.label :name, "Name:" %>
    <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control form-control-user", placeholder: "Enter User's Name..", required: 'required' %>
  </div>

  <div class="form-group">
  	<%= f.label :email, "Email:" %>
  	<%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control form-control-user", placeholder: "Enter User's Email..", required: 'required' %>
  </div>

  <div class="form-group">
  	<%= f.label :roles, class: "d-flex justify-content-between" do %>
  		Role:
  		<%= link_to "#", 'data-toggle': "modal", 'data-target': "#addRoleModal", class: "openRoleModel" do %>
  			<i class="fas fa-plus fa-sm"></i>Add Role
  		<% end %>
  	<% end %>
  	<%= f.select(:roles, @user.roles.collect {|p| p.name }.compact, { include_blank: false }, class: "form-control form-control-user select2-offscreen", id: "select_roles", multiple: "multiple") %>
  </div>

  <div class="form-group">
  	<%= f.label :permissions, "Permissions:" %>
  	<div class="card permissionCard">
      <div class="card-header mb-3">
		  	<ul class="nav nav-tabs" id="myTab" role="tablist">

		  		<% @controller_types.each_with_index do |con, index| %>
					  <li class="nav-item">
					    <a class="nav-link <%= index == 0 ? 'active' : '' %>" id="<%= con.downcase %>-tab" data-toggle="tab" href="#<%= con.downcase %>" role="tab" aria-controls="home" aria-selected="true"><%= make_string_camel_case(con) %></a>
					  </li>
				  <% end %>

				</ul>
			</div>
			<div class="card-body">
				<div class="tab-content" id="myTabContent">
					<% @controller_types.each_with_index do |con, index| %>
				  	<div class="tab-pane fade show <%= index == 0 ? 'active' : '' %>" id="<%= con.downcase %>" role="tabpanel" aria-labelledby="<%= con.downcase %>-tab">
				  		<div class="d-flex flex-wrap">
						  	<%= f.collection_check_boxes :permission_ids, Permission.all.where(controller_type: con), :id, :name do |b| %>
						  		<div class="col-sm-3 d-flex align-items-center selectFormControl">
						  			<%= b.check_box(class: 'permission_checkbox') %>
					      		<%= b.label(class: 'permission_label') %>
						  		</div>
						  	<% end %>
						  </div>
				  	</div>
				  <% end %>
				</div>
			</div>
		</div>
  	
  	<!-- <div class="row">
		  <%# get_controllers.each do |controller| %>
	  		<div class="col-sm-3 selectFormControl">
		    	<%#= f.check_box :permission_ids, { multiple: true }, controller, false %>
		    	<%#= f.label controller %>
		  	</div>
		  <%# end %>
		</div> -->
  </div>

	<%= f.submit (action_name == "new" ? "Create User" : "Update User"), class: "btn btn-primary btn-user btn-block" %>
<% end %>

<!-- Logout Modal-->
<div class="modal fade" id="addRoleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create new Role</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
      	<div class="form-group">
      		<label>Role:</label>
      		<%= text_field_tag 'role', nil, class: "form-control form-control-user" %>
      	</div>
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
        <%= link_to 'Create', "javascript:;", class: 'btn btn-primary addRoleBtn' %>
      </div>
    </div>
  </div>
</div>

<div class="loaderWrapper">
	<img src="/assets/loader.gif">
</div>

<script type="text/javascript">
	$(document).ready(function(){

		// Create Role Ajax Starts

		$('.addRoleBtn').click(function(){
			$(".loaderWrapper").show();
			$.ajax({
			  type: "POST",
			  dataType: 'json',
			  url: "<%= roles_path %>",
			  data: { 
			  	role: {
			  		name: $("#role").val()
			  	}
			  },
			  success(data) {
			  	$("#addRoleModal").modal("hide");
			  	$('#addRoleModal').on('hidden.bs.modal', function() {
					  if(data.status == 403){
				  		$('#content .container-fluid').html("<%= j render(:partial => 'errors/permission_denied') %>");
				  	}else{
					   	if(data["notice"].length > 0){
					   		$.notify(data["notice"] , "success");
					   	}
					   	$(".loaderWrapper").hide();
					  }
					});
			  },
			  error(data) {
			    return false;
			  }
			})
		})

		// Create Role Ajax Ends

		//-----------------------------------------------------//

		// Select2 multiple tags functionality Starts

		$("#select_roles").select2().val($("#select_roles>option").map(function(){return $(this).val();})).trigger("change");
		$("#select_roles").select2({
			placeholder: "Select a role",
	    ajax: {
	      url: "<%= fetch_roles_path %>",
	      dataType: 'json',
	      delay: 250,
	      data: function (params) {
	        return {
	          q: params.term, // search term
	        };
	      },
	      processResults: function (data, params) {
	      	// set value in place of id for select options
	        $.each(data,function(i,v){
	        	v.id = v.name
	        })
	        return {
	          results: data
	          // pagination: {
	          //   more: (params.page * 30) < data.total_count
	          // }
	        };
	      },
	      cache: true
	    },
	    escapeMarkup: function (markup) {
	      return markup; // let our custom formatter work
	    },
	    minimumInputLength: 1,
	    templateResult: function(repo) {
	      return repo.name || repo.text;
	    },
	    templateSelection: function(repo) {
	      return repo.name || repo.text;
	    }
	  });

	  // Select2 multiple tags functionality Ends

	  //----------------------------------------------------//

		// JQuery Validator Starts

	  var validobj = $('.user_form').validate({
	  	ignore: 'input[type=hidden]', // it ignores the hidden fields
	  	errorClass: "error",
	  	errorPlacement: function (error, element) {
        var elem = $(element);
        if(element.attr('name') == "user[roles][]"){
	  			error.insertAfter(element.siblings(".select2"))
        }else{
        	error.insertAfter(element);
        }
      },
      highlight: function (element, errorClass, validClass) {
        var elem = $(element);
        if(elem.hasClass("select2-offscreen")) {
          elem.siblings(".select2").find(".select2-selection").addClass(errorClass);
        }else {
          elem.addClass(errorClass);
        }
      },
      unhighlight: function (element, errorClass, validClass) {
        var elem = $(element);
        if(elem.hasClass("select2-search__field")) {
          $(element).parents('.select2-selection').removeClass(errorClass);
        }else {
          elem.removeClass(errorClass);
        }
      },
			rules: {
				'user[name]': 'required',
				'user[email]': {
					required: true,
      		email: true,
				},
				// 'user[roles][]': 'required'
			},
			messages: {
				'role[name]': 'This field is required',
				'user[email]': {
					required: 'This field is required',
					email: 'Enter a valid email'
				},
				// 'user[roles][]': 'This field is required'
			},
	  	submitHandler: function(form) {
		    form.submit();
		  }
		});

		$(document).on("change", ".select2-offscreen", function() {
      if (!$.isEmptyObject(validobj.submitted)) {
        validobj.form();
      }
    });

    // JQuery Validator Ends

    //------------------------------------------------------//

    // Permission checkbox handling

    $('.permission_checkbox').change(function(){
    	debugger
  		var label = $(this).siblings('.permission_label').text();
  		var label_array = label.split("#")
  		var controller_path = label_array[0]
  		var action_name = label_array[label_array.length - 1]
  		var group_label;
  		var fetch_roles;
  		if(action_name == "edit"){
  			group_label = $(".permission_label:contains(" + controller_path + "#update" + ")")
  		}else if(action_name == "update"){
  			group_label = $(".permission_label:contains(" + controller_path + "#edit" + ")")
  		}else if(action_name == "new"){
  			group_label = $(".permission_label:contains(" + controller_path + "#create" + ")")
  		}else if(action_name == "create"){
  			group_label = $(".permission_label:contains(" + controller_path + "#new" + ")")
  		}
  		if(this.checked){
				group_label.siblings(".permission_checkbox").prop('checked', true);
				if(controller_path == "users"){
					$(".permission_label:contains(roles#fetch_roles)").siblings(".permission_checkbox").prop('checked', true);
				}
			}else{
				group_label.siblings(".permission_checkbox").prop('checked', false);
				if(controller_path == "users"){
					debugger
					if(!$(".permission_label:contains(users#new)").siblings(".permission_checkbox").prop('checked') && !$(".permission_label:contains(users#edit)").siblings(".permission_checkbox").prop('checked')){
						$(".permission_label:contains(roles#fetch_roles)").siblings(".permission_checkbox").prop('checked', false);
					}
				}
			}
    })
	})
</script>

app/views/users/edit.html.erb
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Edit User</h1>
</div>

<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Edit User</h6>
  </div>
  <div class="card-body">
  	<%= render 'form', path: employee_path(@user) %>
  </div>
</div>

app/views/users/index.html.erb
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">All Users</h1>
  <% if have_permission(new_employee_path) %>
    <%= link_to new_employee_path, class: "d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" do %>
      <i class="fas fa-user-plus fa-sm text-white-50"></i> Create User
    <% end %>
  <% end %>
</div>

<!-- DataTales Example -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">All Users</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Roles</th>
            <th>Action</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Roles</th>
            <th>Action</th>
          </tr>
        </tfoot>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= check_presence(user.name) %></td>
              <td><%= check_presence(user.email) %></td>
              <td><%= check_presence(remove_trailing_comma(get_roles(user))) %></td>
              <td>
                <% if have_permission(edit_employee_path(user)) %>
                  <%= link_to edit_employee_path(user), 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Edit" do %>
                    <i class="fas fa-edit"></i>
                  <% end %>
                <% end %>

                <%#= link_to employee_path(user), 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Show" do %>
                  <!-- <i class="fas fa-eye"></i> -->
                <%# end %> 
                <% if have_permission(employee_path(user), "DELETE") %>
                  <%= link_to employee_path(user), method: :delete, data: { confirm: 'Are you sure?' }, 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Delete" do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Create User</h1>
</div>

<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Create User</h6>
  </div>
  <div class="card-body">
  	<%= render 'form', path: employees_path %>
  </div>
</div>