config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

	devise_scope :user do
	  authenticated :user do
	    root 'home#index', as: :authenticated_root
	  end

	  unauthenticated do
	    root 'devise/sessions#new', as: :unauthenticated_root
	  end
	end

  scope '/admin' do
    # Home Controller Starts
    get '/home/index', to: 'home#index'
    # Home Controller Ends

    # Users Controller Starts
    get '/employees', to: 'users#index'
    post '/employees', to: 'users#create'
    get '/employees/new', to: 'users#new', as: 'new_employee'
    get '/employees/:id/edit', to: 'users#edit', as: 'edit_employee'
    get '/employees/:id', to: 'users#show', as: 'employee'
    patch '/employees/:id', to: 'users#update'
    put 'employees/:id', to: 'users#update'
    delete 'employees/:id', to: 'users#destroy'

    get '/fetch_roles', to: 'roles#fetch_roles'
    # Users Controller Ends

    resources :roles, except: [:show]
    resources :categories, except: [:show]
    resources :products, except: [:show]
  end
  
  get '*page', :to => 'errors#not_found', as: :not_found
  get '*page', :to => 'errors#unacceptable', as: :unacceptable
  get '*page', :to => 'errors#internal_error', as: :internal_error
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles

validates_presence_of :name

belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_role, only: [:edit, :update, :destroy]

	def index
		@roles = Role.all
	end

	def new
		@role = Role.new
	end

	def create
		role = Role.new(roles_params)
		if role.save
			respond_to do |format|
				format.html { redirect_to roles_path, notice: 'Role was successfully created.' }
	      format.json { render json: {notice: 'Role was successfully created.'}, status: 200 }
	    end
		else
			respond_to do |format|
				format.html { render :new }
	      format.json { render json: {error: role.errors}, status: :unprocessable_entity }
	    end
		end
	end

	def edit
	end

	def update
		if @role.update_attributes(roles_params)
			redirect_to roles_path, notice: 'Role was successfully updated.'
		else
			render 'edit'
		end
	end

	def destroy
		@role.destroy
		redirect_to roles_path, notice: 'Role was successfully destroyed.'
	end

	def fetch_roles
		@roles = Role.where("name LIKE ?", "%#{params[:q]}%")
		render json: @roles, status: 200
	end


	private

		def roles_params
			params.require(:role).permit(:name)
		end

		def set_role
			@role = Role.find_by(id: params[:id])
		end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for @role, :html => {:class => "role_form"} do |f| %>
	<div class="form-group">
		<%= f.label :name, "Name:" %>
    <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control form-control-user", placeholder: "Enter Role's Name.." %>
  </div>
  <%= f.submit (action_name == "new" ? "Create Role" : "Update Role"), class: "btn btn-primary btn-user btn-block" %>
<% end %>

<script type="text/javascript">
	$(document).ready(function(){
		$('.role_form').validate({
			rules: {
				'role[name]': 'required'
			},
			messages: {
				'role[name]': 'This field is required'
			},
	  	submitHandler: function(form) {
		    form.submit();
		  }
		});
	})
</script>

app/views/roles/edit.html.erb
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Edit Role</h1>
</div>

<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Edit Role</h6>
  </div>
  <div class="card-body">
  	<%= render 'form' %>
  </div>
</div>

app/views/roles/index.html.erb
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">All Roles</h1>
  <% if have_permission(new_role_path) %>
    <%= link_to new_role_path, class: "d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" do %>
      <i class="fas fa-plus fa-sm text-white-50"></i> Create Role
    <% end %>
  <% end %>
</div>

<!-- DataTales Example -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">All Roles</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Name</th>
            <th>Action</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>Name</th>
            <th>Action</th>
          </tr>
        </tfoot>
        <tbody>
          <% @roles.each do |role| %>
            <tr>
              <td><%= check_presence(role.name) %></td>
              <td>
                <% if have_permission(edit_role_path(role)) %>
                  <%= link_to edit_role_path(role), 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Edit" do %>
                    <i class="fas fa-edit"></i>
                  <% end %>
                <% end %>

                <%#= link_to employee_path(user), 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Show" do %>
                  <!-- <i class="fas fa-eye"></i> -->
                <%# end %> 
                <% if have_permission(role_path(role), "DELETE") %>
                  <%= link_to role_path(role), method: :delete, data: { confirm: 'Are you sure?' }, 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Delete" do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/roles/new.html.erb
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Create Role</h1>
</div>

<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Create Role</h6>
  </div>
  <div class="card-body">
  	<%= render 'form' %>
  </div>
</div>