config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

	devise_scope :user do
	  authenticated :user do
	    root 'home#index', as: :authenticated_root
	  end

	  unauthenticated do
	    root 'devise/sessions#new', as: :unauthenticated_root
	  end
	end

  scope '/admin' do
    # Home Controller Starts
    get '/home/index', to: 'home#index'
    # Home Controller Ends

    # Users Controller Starts
    get '/employees', to: 'users#index'
    post '/employees', to: 'users#create'
    get '/employees/new', to: 'users#new', as: 'new_employee'
    get '/employees/:id/edit', to: 'users#edit', as: 'edit_employee'
    get '/employees/:id', to: 'users#show', as: 'employee'
    patch '/employees/:id', to: 'users#update'
    put 'employees/:id', to: 'users#update'
    delete 'employees/:id', to: 'users#destroy'

    get '/fetch_roles', to: 'roles#fetch_roles'
    # Users Controller Ends

    resources :roles, except: [:show]
    resources :categories, except: [:show]
    resources :products, except: [:show]
  end
  
  get '*page', :to => 'errors#not_found', as: :not_found
  get '*page', :to => 'errors#unacceptable', as: :unacceptable
  get '*page', :to => 'errors#internal_error', as: :internal_error
end

app/models/category.rb
class Category < ApplicationRecord
	has_ancestry
	has_and_belongs_to_many :products, :join_table => :categories_products
	validates_presence_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_category, only: [:edit, :update, :destroy]

	def index
		begin
			@categories = Category.all
		rescue Exception => e
			
		end
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render action: 'index', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
	end

	def edit
		
	end

	def update
		if @category.update_attributes(category_params)
			redirect_to categories_path, notice: "Category was successfully updated."
		else
			render 'edit'
		end
	end

	def destroy
		@category.destroy
		redirect_to categories_path, notice: "Category is successfully destroy"
	end

	private

		def set_category
			@category = Category.find_by(id: params[:id])
		end

		def category_params
			params.require(:category).permit(:name, :description, :parent_id)
		end
end

app/helpers/categories_helper.rb
module CategoriesHelper
	def get_parent_category(category)
		if category.parent.present?
			return category.parent.name
		end
	end

	def get_select_categories
		Category.all.each { |c| c.ancestry = c.ancestry.to_s + (c.ancestry != nil ? "/" : '') + c.id.to_s 
      }.sort {|x,y| x.ancestry <=> y.ancestry 
      }.map{ |c| ["-" * (c.depth - 1) + c.name,c.id] 
      }.unshift(["-- none --", nil])
	end

	def get_select_categories_without_selected(cat)
		Category.all.each { |c| c.ancestry = c.ancestry.to_s + (c.ancestry != nil ? "/" : '') + c.id.to_s 
      }.reject{|k| k.name == cat.name
      }.sort {|x,y| x.ancestry <=> y.ancestry 
      }.map{ |c| ["-" * (c.depth - 1) + c.name,c.id] 
      }.unshift(["-- none --", nil])
	end
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => {:class => "category_form"} do |f| %>
	<div class="form-group">
		<%= f.label :name, "Name:" %>
    <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control form-control-user", placeholder: "Enter Category's Name.." %>
  </div>

  <div class="form-group">
  	<%= f.label :description, "Description:" %>
    <%= f.text_field :description, autofocus: true, autocomplete: "name", class: "form-control form-control-user", placeholder: "Enter Category's Description.." %>
  </div>

  <div class="form-group">
  	<%= f.label :parent_id, class: "d-flex justify-content-between" do %>
  		Parent Category:
  		<%#= link_to "#", 'data-toggle': "modal", 'data-target': "#addRoleModal", class: "openRoleModel" do %>
  			<!-- <i class="fas fa-plus fa-sm"></i>Add Role -->
  		<%# end %>
  	<% end %>
  	<%= f.select :parent_id, (action_name == "new" ? get_select_categories : get_select_categories_without_selected(@category)), { include_blank: false }, class: "form-control form-control-user select2-offscreen" %>
  </div>
  <%= f.submit (action_name == "new" ? "Create Category" : "Update Category"), class: "btn btn-primary btn-user btn-block" %>
<% end %>

<script type="text/javascript">
	$(document).ready(function(){
		$('.category_form').validate({
			rules: {
				'category[name]': 'required'
			},
			messages: {
				'category[name]': 'This field is required'
			},
	  	submitHandler: function(form) {
		    form.submit();
		  }
		});
	})
</script>

app/views/categories/edit.html.erb
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Edit Category</h1>
</div>

<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Edit Category</h6>
  </div>
  <div class="card-body">
  	<%= render 'form' %>
  </div>
</div>

app/views/categories/index.html.erb
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">All Categories</h1>
  <% if have_permission(new_category_path) %>
    <%= link_to new_category_path, class: "d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" do %>
      <i class="fas fa-user-plus fa-sm text-white-50"></i> Create Category
    <% end %>
  <% end %>
</div>

<!-- DataTales Example -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">All Categories</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Parent Category</th>
            <th>Action</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Parent Category</th>
            <th>Action</th>
          </tr>
        </tfoot>
        <tbody>
          <% @categories.each do |cat| %>
            <tr>
              <td><%= check_presence(cat.name) %></td>
              <td><%= check_presence(cat.description) %></td>
              <td><%= check_presence(get_parent_category(cat)) %></td>
              <td>
                <% if have_permission(edit_category_path(cat)) %>
                  <%= link_to edit_category_path(cat), 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Edit" do %>
                    <i class="fas fa-edit"></i>
                  <% end %>
                <% end %>

                <%#= link_to employee_path(user), 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Show" do %>
                  <!-- <i class="fas fa-eye"></i> -->
                <%# end %> 
                <% if have_permission(category_path(cat), "DELETE") %>
                  <%= link_to category_path(cat), method: :delete, data: { confirm: 'Are you sure?' }, 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Delete" do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Create Category</h1>
</div>

<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Create Category</h6>
  </div>
  <div class="card-body">
  	<%= render 'form' %>
  </div>
</div>