config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

	devise_scope :user do
	  authenticated :user do
	    root 'home#index', as: :authenticated_root
	  end

	  unauthenticated do
	    root 'devise/sessions#new', as: :unauthenticated_root
	  end
	end

  scope '/admin' do
    # Home Controller Starts
    get '/home/index', to: 'home#index'
    # Home Controller Ends

    # Users Controller Starts
    get '/employees', to: 'users#index'
    post '/employees', to: 'users#create'
    get '/employees/new', to: 'users#new', as: 'new_employee'
    get '/employees/:id/edit', to: 'users#edit', as: 'edit_employee'
    get '/employees/:id', to: 'users#show', as: 'employee'
    patch '/employees/:id', to: 'users#update'
    put 'employees/:id', to: 'users#update'
    delete 'employees/:id', to: 'users#destroy'

    get '/fetch_roles', to: 'roles#fetch_roles'
    # Users Controller Ends

    resources :roles, except: [:show]
    resources :categories, except: [:show]
    resources :products, except: [:show]
  end
  
  get '*page', :to => 'errors#not_found', as: :not_found
  get '*page', :to => 'errors#unacceptable', as: :unacceptable
  get '*page', :to => 'errors#internal_error', as: :internal_error
end

app/models/product.rb
class Product < ApplicationRecord
	validates_presence_of :name, :description, :price
	has_and_belongs_to_many :categories, :join_table => :categories_products
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_product, only: [:edit, :update, :destroy]

	def index
		@products = Product.includes(:categories)
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render action: 'index', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
	end

	def edit

	end

	def update
		if @product.update_attributes(product_params)
			redirect_to products_path, notice: "Product was successfully updated."
		else
			render 'edit'
		end
	end

	def destroy
		@product.destroy
		redirect_to products_path, notice: 'Product was successfully destroyed.'
	end

	private

		def product_params
			params.require(:product).permit(:name, :description, :price, category_ids: [])
		end

		def set_product
			@product = Product.find_by(id: params[:id])
		end
end

app/helpers/products_helper.rb
module ProductsHelper
	def get_product_categories(product)
		categories = ""
		if product.categories.present?
			product.categories.each do |category|
				categories += category.name + ", "
			end
			return categories
		end
	end
end

app/views/products/_form.html.erb
<%= form_for @product, :html => {:class => "product_form"} do |f| %>
	<div class="form-group">
		<%= f.label :name, "Name:" %>
    <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control form-control-user", placeholder: "Enter Product's Name.." %>
  </div>

  <div class="form-group">
  	<%= f.label :description, "Description:" %>
    <%= f.text_field :description, autofocus: true, autocomplete: "description", class: "form-control form-control-user", placeholder: "Enter Product's Description.." %>
  </div>

  <div class="form-group">
    <%= f.label :price, "Price:" %>
    <%= f.text_field :price, autofocus: true, autocomplete: "price", class: "form-control form-control-user", placeholder: "Enter Product's Price.." %>
  </div>

  <div class="form-group">
    <%= f.label :category_ids, "Categories:" %>
    <%= f.select :category_ids, get_select_categories, { include_blank: false }, prompt: "Select Categories", class: "form-control form-control-user select2-offscreen", id: "select_categories", multiple: "multiple" %>
  </div>

  <%= f.submit (action_name == "new" ? "Create Product" : "Update Product"), class: "btn btn-primary btn-user btn-block" %>
<% end %>

<script type="text/javascript">
	$(document).ready(function(){
		var validobj = $('.product_form').validate({
      errorClass: "error",
			rules: {
				'product[name]': 'required',
        'product[description]': 'required',
        'product[price]': 'required',
        'product[category_ids][]': 'required'
			},
			messages: {
				'product[name]': 'This field is required',
        'product[description]': 'This field is required',
        'product[price]': 'This field is required',
        'product[category_ids][]': 'Please select some categories'
			},
      errorPlacement: function (error, element) {
        var elem = $(element);
        if(elem.attr('name') == "product[category_ids][]"){
          error.insertAfter(element.siblings(".select2"))
        }else{
          error.insertAfter(element);
        }
      },
      highlight: function (element, errorClass, validClass) {
        var elem = $(element);
        if(elem.hasClass("select2-offscreen")) {
          elem.siblings(".select2").find(".select2-selection").addClass(errorClass);
        }else {
          elem.addClass(errorClass);
        }
      },
      unhighlight: function (element, errorClass, validClass) {
        var elem = $(element);
        if(elem.hasClass("select2-offscreen")) {
          elem.siblings(".select2").find(".select2-selection").removeClass(errorClass);
        }else {
          elem.removeClass(errorClass);
        }
      },
	  	submitHandler: function(form) {
		    form.submit();
		  }
		});

    $(document).on("change", ".select2-offscreen", function () {
      if (!$.isEmptyObject(validobj.submitted)) {
        validobj.form();
      }
    });

    $("#select_categories").select2({
      placeholder: "Select categories"
    });
	})
</script>

app/views/products/edit.html.erb
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Edit Product</h1>
</div>

<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Edit Product</h6>
  </div>
  <div class="card-body">
  	<%= render 'form' %>
  </div>
</div>

app/views/products/index.html.erb
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">All Products</h1>
  <% if have_permission(new_product_path) %>
    <%= link_to new_product_path, class: "d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" do %>
      <i class="fas fa-user-plus fa-sm text-white-50"></i> Create Product
    <% end %>
  <% end %>
</div>

<!-- DataTales Example -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">All Products</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
            <th>Categories</th>
            <th>Action</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
            <th>Categories</th>
            <th>Action</th>
          </tr>
        </tfoot>
        <tbody>
          <% @products.each do |product| %>
            <tr>
              <td><%= check_presence(product.name) %></td>
              <td><%= check_presence(product.description) %></td>
              <td><%= check_presence(product.price) %></td>
              <td><%= check_presence(remove_trailing_comma(get_product_categories(product))) %></td>
              <td>
                <% if have_permission(edit_product_path(product)) %>
                  <%= link_to edit_product_path(product), 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Edit" do %>
                    <i class="fas fa-edit"></i>
                  <% end %>
                <% end %>

                <%#= link_to employee_path(user), 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Show" do %>
                  <!-- <i class="fas fa-eye"></i> -->
                <%# end %> 
                <% if have_permission(product_path(product), "DELETE") %>
                  <%= link_to product_path(product), method: :delete, data: { confirm: 'Are you sure?' }, 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Delete" do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Create Product</h1>
</div>

<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Create Product</h6>
  </div>
  <div class="card-body">
  	<%= render 'form' %>
  </div>
</div>